// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QNZOA.Data
{
    [Table("Customer")]
    public partial class Customer
    {
        public Customer()
        {
            Projects = new HashSet<Project>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        public byte CustomerType { get; set; }
        [StringLength(250)]
        public string Description { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreatedDate { get; set; }
        [Required]
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [StringLength(250)]
        public string Address { get; set; }
        [StringLength(150)]
        public string Email { get; set; }
        [StringLength(50)]
        public string Phone { get; set; }
        public string Logo { get; set; }
        [StringLength(150)]
        public string Homepage { get; set; }

        [InverseProperty(nameof(Project.Customer))]
        public virtual ICollection<Project> Projects { get; set; }
    }
}