// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QNZOA.Data
{
    [Table("Paymentlog")]
    public partial class Paymentlog
    {
        [Key]
        public int Id { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal Money { get; set; }
        [Required]
        [StringLength(150)]
        public string Description { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreatedDate { get; set; }
        [Required]
        [StringLength(50)]
        public string CreatedBy { get; set; }
        public int ProjectId { get; set; }

        [ForeignKey(nameof(ProjectId))]
        [InverseProperty("Paymentlogs")]
        public virtual Project Project { get; set; }
        [ForeignKey(nameof(ProjectId))]
        [InverseProperty(nameof(ProjectBusiness.Paymentlogs))]
        public virtual ProjectBusiness ProjectNavigation { get; set; }
    }
}