// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QNZOA.Data
{
    [Table("ProjectBusiness")]
    public partial class ProjectBusiness
    {
        public ProjectBusiness()
        {
            Paymentlogs = new HashSet<Paymentlog>();
        }

        [Key]
        public int ProjectId { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal Amount { get; set; }
        [StringLength(250)]
        public string Contract { get; set; }

        [ForeignKey(nameof(ProjectId))]
        [InverseProperty("ProjectBusiness")]
        public virtual Project Project { get; set; }
        [InverseProperty(nameof(Paymentlog.ProjectNavigation))]
        public virtual ICollection<Paymentlog> Paymentlogs { get; set; }
    }
}