// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QNZOA.Data
{
    [Table("TaskList")]
    public partial class TaskList
    {
        public TaskList()
        {
            TaskBadges = new HashSet<TaskBadge>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(100)]
        public string Title { get; set; }
        public string Body { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreatedDate { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        public Guid? Performer { get; set; }
        public short Status { get; set; }
        public int ProjectId { get; set; }
        [Column(TypeName = "numeric(18, 2)")]
        public decimal WorkHours { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? StartTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? FinishTme { get; set; }

        [ForeignKey(nameof(Performer))]
        [InverseProperty(nameof(User.TaskLists))]
        public virtual User PerformerNavigation { get; set; }
        [ForeignKey(nameof(ProjectId))]
        [InverseProperty("TaskLists")]
        public virtual Project Project { get; set; }
        [InverseProperty(nameof(TaskBadge.Task))]
        public virtual ICollection<TaskBadge> TaskBadges { get; set; }
    }
}