// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QNZOA.Data
{
    [Table("TaskBadge")]
    public partial class TaskBadge
    {
        [Key]
        public int TaskId { get; set; }
        [Key]
        public int BadgeId { get; set; }

        [ForeignKey(nameof(BadgeId))]
        [InverseProperty("TaskBadges")]
        public virtual Badge Badge { get; set; }
        [ForeignKey(nameof(TaskId))]
        [InverseProperty(nameof(TaskList.TaskBadges))]
        public virtual TaskList Task { get; set; }
    }
}