// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QNZOA.Data
{
    [Table("User")]
    public partial class User
    {
        public User()
        {
            Projects = new HashSet<Project>();
            Tasks = new HashSet<Task>();
            UserProjects = new HashSet<UserProject>();
            UserRoles = new HashSet<UserRole>();
        }

        [Key]
        public Guid Id { get; set; }
        [Required]
        [StringLength(50)]
        public string Username { get; set; }
        [StringLength(50)]
        public string RealName { get; set; }
        public DateTime? Birthday { get; set; }
        [StringLength(50)]
        public string Mobile { get; set; }
        [Required]
        [StringLength(150)]
        public string Email { get; set; }
        public short Gender { get; set; }
        public bool IsActive { get; set; }
        public DateTime? LastActivityDate { get; set; }
        public string PasswordHash { get; set; }
        [StringLength(150)]
        public string PhotoUrl { get; set; }
        [Column("QQ")]
        [StringLength(50)]
        public string Qq { get; set; }
        public string SecurityStamp { get; set; }
        public DateTime CreateDate { get; set; }

        [InverseProperty(nameof(Project.ManagerNavigation))]
        public virtual ICollection<Project> Projects { get; set; }
        [InverseProperty(nameof(Task.PerformerNavigation))]
        public virtual ICollection<Task> Tasks { get; set; }
        [InverseProperty(nameof(UserProject.User))]
        public virtual ICollection<UserProject> UserProjects { get; set; }
        [InverseProperty(nameof(UserRole.User))]
        public virtual ICollection<UserRole> UserRoles { get; set; }
    }
}