// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QNZOA.Data
{
    [Table("UserProject")]
    public partial class UserProject
    {
        [Key]
        public int ProjectId { get; set; }
        [Key]
        public Guid UserId { get; set; }

        [ForeignKey(nameof(ProjectId))]
        [InverseProperty("UserProjects")]
        public virtual Project Project { get; set; }
        [ForeignKey(nameof(UserId))]
        [InverseProperty("UserProjects")]
        public virtual User User { get; set; }
    }
}